[2024-04-20T16:08:01.075+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-20T16:08:01.270+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v3.second_task scheduled__2024-04-16T00:00:00+00:00 [queued]>
[2024-04-20T16:08:01.309+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v3.second_task scheduled__2024-04-16T00:00:00+00:00 [queued]>
[2024-04-20T16:08:01.313+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-20T16:08:01.495+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): second_task> on 2024-04-16 00:00:00+00:00
[2024-04-20T16:08:01.650+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2383) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-20T16:08:01.692+0000] {standard_task_runner.py:63} INFO - Started process 2416 to run task
[2024-04-20T16:08:01.696+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v3', 'second_task', 'scheduled__2024-04-16T00:00:00+00:00', '--job-id', '310', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpjb82m53b']
[2024-04-20T16:08:01.709+0000] {standard_task_runner.py:91} INFO - Job 310: Subtask second_task
[2024-04-20T16:08:02.073+0000] {task_command.py:426} INFO - Running <TaskInstance: our_first_dag_v3.second_task scheduled__2024-04-16T00:00:00+00:00 [running]> on host e87e2f3305bd
[2024-04-20T16:08:02.335+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='julionevadod' AIRFLOW_CTX_DAG_ID='our_first_dag_v3' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T00:00:00+00:00'
[2024-04-20T16:08:02.336+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-20T16:08:02.353+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-20T16:08:02.364+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task2 and will be running after']
[2024-04-20T16:08:02.377+0000] {subprocess.py:86} INFO - Output:
[2024-04-20T16:08:02.380+0000] {subprocess.py:93} INFO - hey, I am task2 and will be running after
[2024-04-20T16:08:02.382+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-20T16:08:02.384+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-20T16:08:02.430+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v3, task_id=second_task, execution_date=20240416T000000, start_date=20240420T160801, end_date=20240420T160802
[2024-04-20T16:08:02.468+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-20T16:08:02.587+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-20T16:08:02.591+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
