[2024-04-20T16:57:39.894+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-20T16:57:39.913+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v02.greet scheduled__2024-04-19T00:00:00+00:00 [queued]>
[2024-04-20T16:57:39.918+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v02.greet scheduled__2024-04-19T00:00:00+00:00 [queued]>
[2024-04-20T16:57:39.918+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-20T16:57:39.924+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): greet> on 2024-04-19 00:00:00+00:00
[2024-04-20T16:57:39.929+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4031) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-20T16:57:39.929+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v02', 'greet', 'scheduled__2024-04-19T00:00:00+00:00', '--job-id', '352', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmplxr2sv2h']
[2024-04-20T16:57:39.930+0000] {standard_task_runner.py:63} INFO - Started process 4032 to run task
[2024-04-20T16:57:39.930+0000] {standard_task_runner.py:91} INFO - Job 352: Subtask greet
[2024-04-20T16:57:39.959+0000] {task_command.py:426} INFO - Running <TaskInstance: our_dag_with_python_operator_v02.greet scheduled__2024-04-19T00:00:00+00:00 [running]> on host e87e2f3305bd
[2024-04-20T16:57:40.018+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='julionevadod' AIRFLOW_CTX_DAG_ID='our_dag_with_python_operator_v02' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2024-04-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-19T00:00:00+00:00'
[2024-04-20T16:57:40.019+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-20T16:57:40.027+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-20T16:57:40.028+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: greet() missing 1 required positional argument: 'age'
[2024-04-20T16:57:40.038+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v02, task_id=greet, execution_date=20240419T000000, start_date=20240420T165739, end_date=20240420T165740
[2024-04-20T16:57:40.044+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 352 for task greet (greet() missing 1 required positional argument: 'age'; 4032)
[2024-04-20T16:57:40.079+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-20T16:57:40.088+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-20T16:57:40.089+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
