[2024-04-22T17:29:19.380+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-22T17:29:19.393+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v05.greet scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-04-22T17:29:19.397+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v05.greet scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-04-22T17:29:19.397+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-22T17:29:19.402+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): greet> on 2024-04-21 00:00:00+00:00
[2024-04-22T17:29:19.406+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=10027) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-22T17:29:19.406+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v05', 'greet', 'scheduled__2024-04-21T00:00:00+00:00', '--job-id', '360', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmpgxctqyuz']
[2024-04-22T17:29:19.407+0000] {standard_task_runner.py:63} INFO - Started process 10028 to run task
[2024-04-22T17:29:19.407+0000] {standard_task_runner.py:91} INFO - Job 360: Subtask greet
[2024-04-22T17:29:19.432+0000] {task_command.py:426} INFO - Running <TaskInstance: our_dag_with_python_operator_v05.greet scheduled__2024-04-21T00:00:00+00:00 [running]> on host e87e2f3305bd
[2024-04-22T17:29:19.474+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='julionevadod' AIRFLOW_CTX_DAG_ID='our_dag_with_python_operator_v05' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2024-04-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-21T00:00:00+00:00'
[2024-04-22T17:29:19.474+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-22T17:29:19.485+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-22T17:29:19.486+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 23, in greet
    last_name = ti.xcom_pull(task_id="get_name",key="last_name")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'
[2024-04-22T17:29:19.493+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v05, task_id=greet, execution_date=20240421T000000, start_date=20240422T172919, end_date=20240422T172919
[2024-04-22T17:29:19.498+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 360 for task greet (TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'; 10028)
[2024-04-22T17:29:19.509+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-22T17:29:19.516+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T17:29:19.517+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-22T17:30:48.223+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-22T17:30:48.236+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v05.greet scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-04-22T17:30:48.240+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v05.greet scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-04-22T17:30:48.240+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-22T17:30:48.245+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): greet> on 2024-04-21 00:00:00+00:00
[2024-04-22T17:30:48.249+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=10083) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-22T17:30:48.249+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v05', 'greet', 'scheduled__2024-04-21T00:00:00+00:00', '--job-id', '362', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmp2bho0w0p']
[2024-04-22T17:30:48.250+0000] {standard_task_runner.py:63} INFO - Started process 10084 to run task
[2024-04-22T17:30:48.250+0000] {standard_task_runner.py:91} INFO - Job 362: Subtask greet
[2024-04-22T17:30:48.269+0000] {task_command.py:426} INFO - Running <TaskInstance: our_dag_with_python_operator_v05.greet scheduled__2024-04-21T00:00:00+00:00 [running]> on host e87e2f3305bd
[2024-04-22T17:30:48.302+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='julionevadod' AIRFLOW_CTX_DAG_ID='our_dag_with_python_operator_v05' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2024-04-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-21T00:00:00+00:00'
[2024-04-22T17:30:48.302+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-22T17:30:48.315+0000] {logging_mixin.py:188} INFO - Hello World! My name is Jerry Fridman and I am 24 yeasrs old.
[2024-04-22T17:30:48.315+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-22T17:30:48.315+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-22T17:30:48.319+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=our_dag_with_python_operator_v05, task_id=greet, execution_date=20240421T000000, start_date=20240422T173048, end_date=20240422T173048
[2024-04-22T17:30:48.352+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-22T17:30:48.362+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T17:30:48.362+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
