[2024-04-24T16:56:57.372+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-24T16:56:57.393+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v02.get_matplotlib scheduled__2024-04-23T00:00:00+00:00 [queued]>
[2024-04-24T16:56:57.398+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v02.get_matplotlib scheduled__2024-04-23T00:00:00+00:00 [queued]>
[2024-04-24T16:56:57.399+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-24T16:56:57.406+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_matplotlib> on 2024-04-23 00:00:00+00:00
[2024-04-24T16:56:57.411+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v02', 'get_matplotlib', 'scheduled__2024-04-23T00:00:00+00:00', '--job-id', '438', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmpv0hyim4j']
[2024-04-24T16:56:57.413+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=534) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-24T16:56:57.413+0000] {standard_task_runner.py:91} INFO - Job 438: Subtask get_matplotlib
[2024-04-24T16:56:57.414+0000] {standard_task_runner.py:63} INFO - Started process 535 to run task
[2024-04-24T16:56:57.444+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_python_dependencies_v02.get_matplotlib scheduled__2024-04-23T00:00:00+00:00 [running]> on host ad2a90cae733
[2024-04-24T16:56:57.495+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='julionevadod' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies_v02' AIRFLOW_CTX_TASK_ID='get_matplotlib' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-23T00:00:00+00:00'
[2024-04-24T16:56:57.496+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-24T16:56:57.504+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-24T16:56:57.505+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 11, in get_matplotlib
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-04-24T16:56:57.512+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_python_dependencies_v02, task_id=get_matplotlib, execution_date=20240423T000000, start_date=20240424T165657, end_date=20240424T165657
[2024-04-24T16:56:57.517+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 438 for task get_matplotlib (No module named 'matplotlib'; 535)
[2024-04-24T16:56:57.556+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-24T16:56:57.563+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-24T16:56:57.563+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-24T17:00:33.373+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-24T17:00:33.424+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v02.get_matplotlib scheduled__2024-04-23T00:00:00+00:00 [queued]>
[2024-04-24T17:00:33.448+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v02.get_matplotlib scheduled__2024-04-23T00:00:00+00:00 [queued]>
[2024-04-24T17:00:33.448+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-24T17:00:33.460+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_matplotlib> on 2024-04-23 00:00:00+00:00
[2024-04-24T17:00:33.502+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v02', 'get_matplotlib', 'scheduled__2024-04-23T00:00:00+00:00', '--job-id', '444', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmpvl43m_1q']
[2024-04-24T17:00:33.507+0000] {standard_task_runner.py:91} INFO - Job 444: Subtask get_matplotlib
[2024-04-24T17:00:33.508+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=348) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-24T17:00:33.510+0000] {standard_task_runner.py:63} INFO - Started process 350 to run task
[2024-04-24T17:00:33.604+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_python_dependencies_v02.get_matplotlib scheduled__2024-04-23T00:00:00+00:00 [running]> on host 93ff25214622
[2024-04-24T17:00:33.730+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='julionevadod' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies_v02' AIRFLOW_CTX_TASK_ID='get_matplotlib' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-23T00:00:00+00:00'
[2024-04-24T17:00:33.731+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-24T17:00:34.613+0000] {logging_mixin.py:188} INFO - matplotlib with version: 3.8.4
[2024-04-24T17:00:34.614+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-24T17:00:34.614+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-24T17:00:34.641+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_with_python_dependencies_v02, task_id=get_matplotlib, execution_date=20240423T000000, start_date=20240424T170033, end_date=20240424T170034
[2024-04-24T17:00:34.714+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-24T17:00:34.797+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-24T17:00:34.800+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
